# Utiliser une image Node.js version 18
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port 5000 (ou le port utilisé par votre backend)
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["npm", "start"]